<a href="https://colab.research.google.com/github/Masoomas98/UNetWaveDeform/blob/main/Pytorch/PyTorch_fudamental00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Sat Jul  8 21:18:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot
print(torch.__version__)

2.0.1+cu118


In [ ]:
##Tensors

##Creating tensors

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()
#get scalar as a python integer

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix.ndim


2

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[9,8,7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [9, 8, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape
#([1,3,3]) 1 CORRESPONDS to the first outer bracket second 3 corresponds to 3 square brackets and last 3 corresponds to 3 elements

torch.Size([1, 3, 3])

In [ ]:
#Random tensors

Random tensors

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using torch.rand() and passing in the size parameter.

In [ ]:
random_tensor = torch.rand(1,3,4)

In [ ]:
random_tensor

tensor([[[0.6945, 0.7825, 0.2974, 0.7523],
         [0.8289, 0.9321, 0.1000, 0.5007],
         [0.8293, 0.8852, 0.4303, 0.8911]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([1, 3, 4])

In [ ]:
random_image_tensor = torch.rand(size=(224,224,3)) # 224 height, 224 width, 3 means the R,G,B colours
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Zeros and ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#Creating a range of tensors and tensors-like
one_to_ten= torch.arange(start =1, end=11, step=1) #tensors of 1 till 10

In [ ]:
#creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros #same shape as one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Float 32 tensor
#Tensor data type is one of the 3 big errors we'll run into usinf deep learning
#the three errors are: shape, type and tensors not on the right device
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #What data type is the tensor eg float16, float32 etc
                               device=None, #"cuda" for GPU #what device is your tensor on
                               requires_grad=False) #whether to track gradients with these tensors or not
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
tensor_multiplied = float_16_tensor*float_32_tensor

In [ ]:
tensor_multiplied.dtype

torch.float32

In [ ]:
#In order to se the errors in pytorch with tensor the. three checks are:
#tensor.dtype.      tensor.device.      tensor.shape

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7868, 0.0041, 0.5913, 0.5122],
        [0.7238, 0.4808, 0.6362, 0.7717],
        [0.9057, 0.6559, 0.4373, 0.4196]])

In [ ]:
print(some_tensor)
print(f"datatype:{some_tensor.type(torch.float16)}")
print(f"shape:{some_tensor.shape}")
print(f"device:{some_tensor.device}")

tensor([[0.7868, 0.0041, 0.5913, 0.5122],
        [0.7238, 0.4808, 0.6362, 0.7717],
        [0.9057, 0.6559, 0.4373, 0.4196]])
datatype:tensor([[0.7866, 0.0041, 0.5913, 0.5122],
        [0.7236, 0.4807, 0.6362, 0.7715],
        [0.9058, 0.6558, 0.4373, 0.4197]], dtype=torch.float16)
shape:torch.Size([3, 4])
device:cpu


In [ ]:
from torch.functional import Tensor
#Manipulating tensors
Tensor = torch.tensor([2,4,6])
Tensor+50


tensor([52, 54, 56])

In [ ]:
Tensor-2

tensor([0, 2, 4])

In [ ]:
Tensor*5

tensor([10, 20, 30])

In [ ]:
#Try pytorch inbuilt
torch.mul(Tensor,10)

tensor([20, 40, 60])

In [ ]:
torch.add(Tensor,12)

tensor([14, 16, 18])

**
Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it. **

In [ ]:
#Element wise multpilication
Multip = Tensor * Tensor
print(Tensor,"*", Tensor, "=", Multip)

tensor([2, 4, 6]) * tensor([2, 4, 6]) = tensor([ 4, 16, 36])


In [ ]:
#Matrix multiplication
%%time
torch.matmul(Tensor,Tensor)

CPU times: user 110 µs, sys: 18 µs, total: 128 µs
Wall time: 207 µs


tensor(56)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,3))
#Matrix multiplication
#Inner dimensions must match and resulting matrix has outer dimensions

tensor([[0.6489, 0.6971, 0.2676],
        [0.9474, 0.9212, 0.6229]])

In [ ]:
#If shapes of tensors arent fixed we can take transpose of one or the other for multiplying:
Tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
Tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
multiply_ = torch.matmul(Tensor_A,Tensor_B.T)
multiply_

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#Find min, max,mean, sum etc (tensor aggregation) Pytorch inbuilt functions
x = torch.arange(0,10,2)


x.max(), torch.max(x)

(tensor(8), tensor(8))

In [ ]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
x.type(torch.float16).mean()

tensor(4., dtype=torch.float16)

In [ ]:
x.sum()

tensor(20)

In [ ]:
###Positional mean, max :argmin,argmax
x.argmin() #find the position in tesnor that has a minimum value in that tensor --> returns the index value where minimum value occurs

tensor(0)

In [ ]:
x.argmax()

tensor(4)

In [ ]:
x

tensor([0, 2, 4, 6, 8])

In [ ]:
x[4]

tensor(8)

In [ ]:
#Reshaping, stacking and viewing, squeezing and unsqueezing tensors


# Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

Method	One-line description
torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
torch.Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.
Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

# Reshaping - reshapes an input tensor to a defined shape
• View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
• Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
• Squeeze - removes all 1 dimensions from a tensor
• Unsqueeze - add a 1 dimension to a target tensor
• Permute - Return a view of the input with dimensions permuted (swapped) in a certain

In [ ]:
y = torch.arange(1.,10)
z = torch.arange(1.,11)
y,z

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
y_reshaped = y.reshape(1,9)
z_reshaped = z.reshape(2,5)
y_reshaped, z_reshaped

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]))

In [ ]:
y_reshape = y.reshape(9,1)
z_reshape = z.reshape(5,2)
y_reshape, z_reshape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]))

In [ ]:
#VIEW
s = y.view(1,9)
s, s.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
s[:,0]=5 #changing first element of z which is a view of y
s,y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stacking tensors on top of each other
y_stack = torch.stack([y,y,y],dim=0)
y_stack, y_stack.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([3, 9]))

In [ ]:
y_stack = torch.stack([y,y,y],dim=1)
y_stack,y_stack.shape

(tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [ ]:
#SQUEEZE
#Removes all single dimensions from a tensor

r = y_reshape.squeeze()
r, r.shape, y_reshape.shape, y_reshape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.Size([9, 1]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
#UNSQUEEZE
#Adds an extra dimension to a tensor
u= z_reshape.unsqueeze(dim=0)

print("originals")
z_reshape, z_reshape.shape,u,u.shape


originals


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 7.,  8.],
          [ 9., 10.]]]),
 torch.Size([1, 5, 2]))

In [ ]:
u= z_reshape.unsqueeze(dim=1)

print("originals")
z_reshape, z_reshape.shape,u,u.shape

originals


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 tensor([[[ 1.,  2.]],
 
         [[ 3.,  4.]],
 
         [[ 5.,  6.]],
 
         [[ 7.,  8.]],
 
         [[ 9., 10.]]]),
 torch.Size([5, 1, 2]))

In [ ]:
#Permute tensors change them in a specific order
tensor = torch.rand(size=(224,224,3))

permute_tensor = torch.permute(tensor, dims=(2,1,0))
tensor.shape, tensor,permute_tensor, permute_tensor.shape

(torch.Size([224, 224, 3]),
 tensor([[[0.9628, 0.7707, 0.4041],
          [0.3609, 0.7118, 0.3614],
          [0.0920, 0.9029, 0.4201],
          ...,
          [0.1462, 0.8871, 0.3171],
          [0.1248, 0.6544, 0.2217],
          [0.1512, 0.6111, 0.8219]],
 
         [[0.3534, 0.2691, 0.3741],
          [0.3502, 0.2797, 0.4648],
          [0.5090, 0.1508, 0.6349],
          ...,
          [0.5355, 0.7920, 0.4810],
          [0.3763, 0.4847, 0.9869],
          [0.3744, 0.9557, 0.0256]],
 
         [[0.2108, 0.7813, 0.7062],
          [0.1175, 0.7360, 0.2104],
          [0.7584, 0.3968, 0.2733],
          ...,
          [0.5096, 0.3694, 0.3127],
          [0.1404, 0.0018, 0.0194],
          [0.3691, 0.7847, 0.8312]],
 
         ...,
 
         [[0.6500, 0.5618, 0.5761],
          [0.3642, 0.0350, 0.1505],
          [0.0090, 0.6837, 0.3353],
          ...,
          [0.1643, 0.1914, 0.3427],
          [0.1889, 0.4993, 0.0244],
          [0.5029, 0.4150, 0.2612]],
 
         [[0.9436, 0

In [ ]:
tensor[0,0,0] = 0.1000
tensor

tensor([[[0.1000, 0.7707, 0.4041],
         [0.3609, 0.7118, 0.3614],
         [0.0920, 0.9029, 0.4201],
         ...,
         [0.1462, 0.8871, 0.3171],
         [0.1248, 0.6544, 0.2217],
         [0.1512, 0.6111, 0.8219]],

        [[0.3534, 0.2691, 0.3741],
         [0.3502, 0.2797, 0.4648],
         [0.5090, 0.1508, 0.6349],
         ...,
         [0.5355, 0.7920, 0.4810],
         [0.3763, 0.4847, 0.9869],
         [0.3744, 0.9557, 0.0256]],

        [[0.2108, 0.7813, 0.7062],
         [0.1175, 0.7360, 0.2104],
         [0.7584, 0.3968, 0.2733],
         ...,
         [0.5096, 0.3694, 0.3127],
         [0.1404, 0.0018, 0.0194],
         [0.3691, 0.7847, 0.8312]],

        ...,

        [[0.6500, 0.5618, 0.5761],
         [0.3642, 0.0350, 0.1505],
         [0.0090, 0.6837, 0.3353],
         ...,
         [0.1643, 0.1914, 0.3427],
         [0.1889, 0.4993, 0.0244],
         [0.5029, 0.4150, 0.2612]],

        [[0.9436, 0.0411, 0.4308],
         [0.7798, 0.8456, 0.3633],
         [0.

In [ ]:
#Indexing with pytorch
example = torch.arange(1,11).reshape(1,2,5)
example, example.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]),
 torch.Size([1, 2, 5]))

In [ ]:
#Let's index on our new tensor
example,example[0]

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]))

In [ ]:
example[0][0]

tensor([1, 2, 3, 4, 5])

In [ ]:
example[0][0][0]

tensor(1)

In [ ]:
example[0][1][3]

tensor(9)

In [ ]:
example[:,:,1]

tensor([[2, 7]])

In [ ]:
example[:,1,3]

tensor([9])

# **NUMPY TO TENSOR**



In [ ]:
import numpy as np
import torch

In [ ]:
array = np.arange(0.0,8.0)

tensor = torch.from_numpy(array)
array =array+1
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

*the default datatype for numpy is float 64 whereas for tensor is float 32*

# **Tensor** to **numpy**

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor=tensor+1
#numpy_tensor =tensor.numpy()
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [ ]:
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)
print(random_tensorA)
print(random_tensorB)
print(random_tensorA==random_tensorB)

tensor([[0.0603, 0.7702, 0.2177, 0.6321],
        [0.7797, 0.6542, 0.3602, 0.9754],
        [0.1280, 0.7395, 0.6418, 0.6592]])
tensor([[0.8680, 0.4759, 0.3721, 0.7567],
        [0.3637, 0.7620, 0.1086, 0.8564],
        [0.7269, 0.6518, 0.3446, 0.3890]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#random but reproducible tensors
#Set the random seed
Random_seed = 42 #could be 77, 0 ,1234
torch.manual_seed(Random_seed)
random_tensorC = torch.rand(3,4)
torch.manual_seed(Random_seed)
random_tensorD = torch.rand(3,4)
print(random_tensorC)
print(random_tensorD)
print(random_tensorC==random_tensorD)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#Running tensors and pytorch on the GPUs
#GPUs = faster computation on numbers, thanKs to CUDA, NVIDIA hardware+pytorch working behind
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

In [ ]:
#Let's use GPU , putting tensors and models on GPU
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#Moving tensors back to cpu
#However if device is gpu we cant use it convert to numpy array, that part is done in cpu
#so to do that you convert tensor in cpu to numpy then back to gpu
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu.device


device(type='cuda', index=0)